let age = 17

if(100 < age >= 25){
    console.log('You can rent a car.');
} else if(age > 130){
    console.log('Haha! A vampire!')
} else if(age >= 21){
    console.log('You can drink.');
} else if(age >= 18){
    console.log('You can vote!');
} else if(age < 18){
    console.log("Sorry, you're too young to do anything.");
}


let age2 = 12

if(100 < age2 >= 25){
    console.log('You can rent a car.');
} else if(age2 > 130){
    console.log('Haha! A vampire!')
} else if(age2 >= 21){
    console.log('You can drink.');
} else if(age2 >= 18){
    console.log('You can vote!');
} else{
    console.log("Sorry, you're too young to do anything.");
}